[phases.setup]
nixPkgs = ["jdk17", "maven"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[start]
cmd = "java -jar target/hub-0.0.1-SNAPSHOT.jar"

[variables]
SPRING_PROFILES_ACTIVE = "prod"
